import type { ShaderDevFieldDef } from "shader-panel"
import type { AccentShaderV2Config } from "./accent-shader-v2-config"

export const ACCENT_SHADER_V2_DEV_FIELDS: ShaderDevFieldDef<AccentShaderV2Config>[] =
  [
    { type: "section", title: "Animation" },
    {
      type: "slider",
      key: "speed",
      label: "Speed",
      min: 0,
      max: 2,
      step: 0.01,
    },
    {
      type: "slider",
      key: "driftSpeed",
      label: "Drift speed",
      min: 0,
      max: 24,
      step: 0.5,
    },
    { type: "section", title: "Background" },
    { type: "color", key: "bgColor", label: "Background" },
    { type: "section", title: "Depth / Wave" },
    {
      type: "slider",
      key: "waveAmp",
      label: "Wave amplitude",
      min: 0,
      max: 4,
      step: 0.02,
    },
    {
      type: "slider",
      key: "waveScale",
      label: "Wave scale",
      min: 0.1,
      max: 10,
      step: 0.05,
    },
    {
      type: "slider",
      key: "waveSpeed",
      label: "Wave speed",
      min: 0,
      max: 4,
      step: 0.02,
    },
    {
      type: "slider",
      key: "waveTurb",
      label: "Wave turbulence",
      min: 0,
      max: 3,
      step: 0.01,
    },
    {
      type: "slider",
      key: "depthParallax",
      label: "Depth parallax (px)",
      min: 0,
      max: 100,
      step: 0.5,
    },
    {
      type: "slider",
      key: "depthSize",
      label: "Depth size influence",
      min: 0,
      max: 2.5,
      step: 0.02,
    },
    {
      type: "slider",
      key: "depthBright",
      label: "Depth brightness influence",
      min: 0,
      max: 2.5,
      step: 0.02,
    },
    { type: "section", title: "Wisps" },
    {
      type: "slider",
      key: "cellSize",
      label: "Cell size",
      min: 3,
      max: 16,
      step: 0.1,
    },
    {
      type: "slider",
      key: "wispStretch",
      label: "Wisp stretch",
      min: 0.2,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "visibleThreshold",
      label: "Visible threshold",
      min: 0,
      max: 0.5,
      step: 0.01,
    },
    {
      type: "slider",
      key: "visibleThresholdReveal",
      label: "Visible (reveal)",
      min: 0,
      max: 0.3,
      step: 0.01,
    },
    {
      type: "slider",
      key: "dotRadius",
      label: "Dot radius",
      min: 0.2,
      max: 2,
      step: 0.05,
    },
    {
      type: "slider",
      key: "dotRadiusReveal",
      label: "Dot radius (reveal)",
      min: 0.2,
      max: 2.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "dotSoft",
      label: "Dot softness",
      min: 0.05,
      max: 0.8,
      step: 0.01,
    },
    {
      type: "slider",
      key: "bloomSpread",
      label: "Bloom spread",
      min: 0.5,
      max: 2,
      step: 0.05,
    },
    {
      type: "slider",
      key: "bloomSpreadReveal",
      label: "Bloom spread (reveal)",
      min: 0.5,
      max: 2.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "bloomNearSigma",
      label: "Bloom near σ",
      min: 1,
      max: 20,
      step: 0.5,
    },
    {
      type: "slider",
      key: "bloomNearAmp",
      label: "Bloom near amp",
      min: 0,
      max: 0.4,
      step: 0.01,
    },
    {
      type: "slider",
      key: "bloomFarSigma",
      label: "Bloom far σ",
      min: 4,
      max: 40,
      step: 0.5,
    },
    {
      type: "slider",
      key: "bloomFarAmp",
      label: "Bloom far amp",
      min: 0,
      max: 0.3,
      step: 0.01,
    },
    {
      type: "slider",
      key: "coreAmp",
      label: "Core amp",
      min: 0,
      max: 0.4,
      step: 0.01,
    },
    {
      type: "slider",
      key: "overlapBloom",
      label: "Overlap bloom",
      min: 0,
      max: 0.6,
      step: 0.01,
    },
    {
      type: "slider",
      key: "shimmerAmp",
      label: "Shimmer depth",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "shimmerWaveSpeed",
      label: "Shimmer sweep speed",
      min: 0,
      max: 2,
      step: 0.02,
    },
    {
      type: "slider",
      key: "shimmerWaveScale",
      label: "Shimmer sweep width",
      min: 0.5,
      max: 8,
      step: 0.1,
    },
    {
      type: "slider",
      key: "shimmerNoiseScale",
      label: "Shimmer noise size",
      min: 0.4,
      max: 6,
      step: 0.05,
    },
    {
      type: "slider",
      key: "shimmerNoiseSpeed",
      label: "Shimmer noise drift",
      min: 0,
      max: 1.5,
      step: 0.02,
    },
    {
      type: "slider",
      key: "radialFadeStart",
      label: "Radial fade start",
      min: 0,
      max: 1.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "radialFadeEnd",
      label: "Radial fade end",
      min: 0.5,
      max: 2.5,
      step: 0.05,
    },
    { type: "section", title: "Lightning bolts" },
    {
      type: "slider",
      key: "boltSpeed",
      label: "Bolt travel speed (1 ≈ 1s)",
      min: 0.25,
      max: 3,
      step: 0.05,
    },
    {
      type: "slider",
      key: "boltSpawnRate",
      label: "Bolt spawn rate",
      min: 0.05,
      max: 1.5,
      step: 0.02,
    },
    {
      type: "slider",
      key: "boltActiveThreshold",
      label: "Bolt activity (higher = more)",
      min: 0,
      max: 0.95,
      step: 0.02,
    },
    {
      type: "slider",
      key: "boltCount",
      label: "Bolt count",
      min: 1,
      max: 10,
      step: 1,
    },
    {
      type: "slider",
      key: "boltWidth",
      label: "Bolt core width",
      min: 0.3,
      max: 2.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "boltHaloWidth",
      label: "Bolt halo width",
      min: 1,
      max: 10,
      step: 0.1,
    },
    {
      type: "slider",
      key: "boltAmp",
      label: "Bolt brightness",
      min: 0,
      max: 2,
      step: 0.02,
    },
    {
      type: "slider",
      key: "boltPulseLength",
      label: "Bolt fade-out window",
      min: 0.04,
      max: 0.85,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltSteps",
      label: "Bolt path hops",
      min: 4,
      max: 10,
      step: 1,
    },
    {
      type: "slider",
      key: "boltStartExtend",
      label: "Bolt start below (× grid height)",
      min: 0,
      max: 1.5,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltEndExtend",
      label: "Bolt end above (× grid height)",
      min: 0,
      max: 0.45,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltFromCenterMin",
      label: "From center (min)",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltFromCenterMax",
      label: "From center (max)",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltEdgeBias",
      label: "Bolt edge bias (0=center, 1=flanks)",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltCenterExclusion",
      label: "Center dead zone (grid fraction)",
      min: 0,
      max: 0.45,
      step: 0.01,
    },
    {
      type: "slider",
      key: "boltSpread",
      label: "Bolt outward spread",
      min: 0.2,
      max: 50,
      step: 0.5,
    },
    { type: "section", title: "Mouse reveal" },
    {
      type: "slider",
      key: "revealRadius",
      label: "Reveal radius",
      min: 40,
      max: 1400,
      step: 10,
    },
    {
      type: "slider",
      key: "revealInner",
      label: "Reveal inner",
      min: 0.05,
      max: 0.8,
      step: 0.05,
    },
    {
      type: "slider",
      key: "brightnessRevealBoost",
      label: "Reveal brightness",
      min: 0,
      max: 1.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "mouseRevealAmp",
      label: "Mouse reveal strength",
      min: 0,
      max: 2.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "mouseMotionSensitivity",
      label: "Mouse motion sensitivity (px)",
      min: 1,
      max: 24,
      step: 0.5,
    },
    {
      type: "slider",
      key: "mouseRevealFadeMs",
      label: "Mouse reveal fade (ms)",
      min: 150,
      max: 1400,
      step: 25,
    },
    { type: "section", title: "Bottom beam" },
    { type: "color", key: "beamColor", label: "Beam color" },
    {
      type: "slider",
      key: "beamYOffset",
      label: "Beam Y offset",
      min: -0.2,
      max: 0.2,
      step: 0.005,
    },
    {
      type: "slider",
      key: "beamRx",
      label: "Beam RX",
      min: 80,
      max: 600,
      step: 10,
    },
    {
      type: "slider",
      key: "beamRy",
      label: "Beam RY",
      min: 40,
      max: 400,
      step: 10,
    },
    {
      type: "slider",
      key: "semiStart",
      label: "Semi start",
      min: 0.3,
      max: 1.5,
      step: 0.05,
    },
    {
      type: "slider",
      key: "semiEnd",
      label: "Semi end",
      min: 0.5,
      max: 2,
      step: 0.05,
    },
    {
      type: "slider",
      key: "semiAmp",
      label: "Semi amp",
      min: 0,
      max: 1,
      step: 0.05,
    },
    {
      type: "slider",
      key: "haloRyScale",
      label: "Halo RY scale",
      min: 1,
      max: 5,
      step: 0.1,
    },
    {
      type: "slider",
      key: "haloSigma",
      label: "Halo σ",
      min: 0.1,
      max: 1.2,
      step: 0.05,
    },
    {
      type: "slider",
      key: "haloAmp",
      label: "Halo amp",
      min: 0,
      max: 1,
      step: 0.05,
    },
    {
      type: "slider",
      key: "coreBandY",
      label: "Core band Y",
      min: 0.005,
      max: 0.08,
      step: 0.001,
    },
    {
      type: "slider",
      key: "coreBandX",
      label: "Core band X",
      min: 50,
      max: 500,
      step: 10,
    },
    {
      type: "slider",
      key: "coreBandAmp",
      label: "Core band amp",
      min: 0,
      max: 0.5,
      step: 0.01,
    },
    {
      type: "slider",
      key: "heatPulseSpeed",
      label: "Heat pulse speed",
      min: 0,
      max: 4,
      step: 0.05,
    },
    {
      type: "slider",
      key: "heatRippleSpeed",
      label: "Heat ripple speed",
      min: 0,
      max: 4,
      step: 0.05,
    },
    {
      type: "slider",
      key: "heatRippleScale",
      label: "Heat ripple scale",
      min: 4,
      max: 40,
      step: 1,
    },
    {
      type: "slider",
      key: "heatMaskSigma",
      label: "Heat mask σ",
      min: 0.1,
      max: 1,
      step: 0.05,
    },
    {
      type: "slider",
      key: "heatPulseAmp",
      label: "Heat pulse amp",
      min: 0,
      max: 0.12,
      step: 0.005,
    },
    {
      type: "slider",
      key: "heatRippleAmp",
      label: "Heat ripple amp",
      min: 0,
      max: 0.08,
      step: 0.002,
    },
    {
      type: "slider",
      key: "beamBottomFade",
      label: "Beam bottom fade",
      min: 0,
      max: 0.05,
      step: 0.001,
    },
    { type: "section", title: "Mouse illumination" },
    {
      type: "slider",
      key: "illumRadius",
      label: "Illum radius",
      min: 40,
      max: 1400,
      step: 10,
    },
    { type: "color", key: "illumColor", label: "Illum color" },
    {
      type: "slider",
      key: "illumAmp",
      label: "Illum amp",
      min: 0,
      max: 0.4,
      step: 0.01,
    },
  ]
