import type { ShaderDevFieldDef } from "shader-panel"
import type { ComboShaderConfig } from "./combo-shader-config"

export const COMBO_SHADER_DEV_FIELDS: ShaderDevFieldDef<ComboShaderConfig>[] = [
  { type: "section", title: "Stage" },
  { type: "color", key: "bgColor", label: "Background" },

  { type: "section", title: "Particle field" },
  {
    type: "slider",
    key: "planeWidth",
    label: "Field width",
    min: 10,
    max: 120,
    step: 1,
  },
  {
    type: "slider",
    key: "planeHeight",
    label: "Field height",
    min: 10,
    max: 120,
    step: 1,
  },
  {
    type: "slider",
    key: "gridSize",
    label: "Grid resolution",
    min: 60,
    max: 360,
    step: 4,
  },
  {
    type: "slider",
    key: "driftSpeed",
    label: "Drift up speed",
    min: 0,
    max: 6,
    step: 0.05,
  },

  { type: "section", title: "Wave noise" },
  {
    type: "slider",
    key: "wavesScale",
    label: "Wave scale",
    min: 0.5,
    max: 10,
    step: 0.1,
  },
  {
    type: "slider",
    key: "waveSpeedX",
    label: "Wave speed X",
    min: -0.3,
    max: 0.3,
    step: 0.005,
  },
  {
    type: "slider",
    key: "waveSpeedY",
    label: "Wave speed Y",
    min: -0.3,
    max: 0.3,
    step: 0.005,
  },
  {
    type: "slider",
    key: "displacement",
    label: "Z displacement",
    min: 0,
    max: 12,
    step: 0.05,
  },
  {
    type: "slider",
    key: "twist",
    label: "Twist amount",
    min: 0,
    max: 3,
    step: 0.01,
  },

  { type: "section", title: "Wave influence" },
  {
    type: "slider",
    key: "waveRadius",
    label: "Influence radius",
    min: 0,
    max: 30,
    step: 0.1,
  },
  {
    type: "slider",
    key: "waveSoft",
    label: "Edge softness",
    min: 0.1,
    max: 20,
    step: 0.1,
  },
  {
    type: "slider",
    key: "wavePulseSpeed",
    label: "Breath rate",
    min: 0,
    max: 3,
    step: 0.01,
  },
  {
    type: "slider",
    key: "wavePulseAmp",
    label: "Breath amount",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    type: "slider",
    key: "waveBreathBias",
    label: "Breath bias (low = symmetric)",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    type: "slider",
    key: "waveStrength",
    label: "Influence strength",
    min: 0,
    max: 2,
    step: 0.01,
  },
  {
    type: "slider",
    key: "waveBoost",
    label: "Peak brightness boost",
    min: 0,
    max: 4,
    step: 0.01,
  },
  {
    type: "slider",
    key: "waveAspect",
    label: "Vertical aspect",
    min: 0.5,
    max: 3,
    step: 0.01,
  },
  {
    type: "slider",
    key: "waveBoundaryAmp",
    label: "Organic edge amp",
    min: 0,
    max: 8,
    step: 0.05,
  },
  {
    type: "slider",
    key: "waveBoundaryScale",
    label: "Organic edge scale",
    min: 0.02,
    max: 1,
    step: 0.01,
  },
  {
    type: "slider",
    key: "waveTravelSpeed",
    label: "Travel up speed",
    min: 0,
    max: 6,
    step: 0.05,
  },
  {
    type: "slider",
    key: "waveTravelRange",
    label: "Travel range",
    min: 0,
    max: 60,
    step: 0.5,
  },

  { type: "section", title: "Particle size" },
  {
    type: "slider",
    key: "pointSize",
    label: "Calm size",
    min: 0.2,
    max: 8,
    step: 0.1,
  },
  {
    type: "slider",
    key: "pointSizePeak",
    label: "Wave peak size",
    min: 0.2,
    max: 12,
    step: 0.1,
  },
  {
    type: "slider",
    key: "sizeAttenuation",
    label: "Distance falloff",
    min: 0,
    max: 1200,
    step: 10,
  },

  { type: "section", title: "Brightness / shimmer" },
  {
    type: "slider",
    key: "valleyBrightness",
    label: "Valley brightness",
    min: 0,
    max: 2,
    step: 0.01,
  },
  {
    type: "slider",
    key: "peakBrightness",
    label: "Peak brightness",
    min: 0,
    max: 3,
    step: 0.01,
  },
  {
    type: "slider",
    key: "visibleThreshold",
    label: "Hide fraction (calm)",
    min: 0,
    max: 0.9,
    step: 0.01,
  },
  {
    type: "slider",
    key: "shimmerAmp",
    label: "Shimmer amp",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    type: "slider",
    key: "shimmerSpeed",
    label: "Shimmer speed",
    min: 0,
    max: 6,
    step: 0.05,
  },

  { type: "section", title: "Colors" },
  { type: "color", key: "calmColor", label: "Calm wisps" },
  { type: "color", key: "peakColor", label: "Wave peak" },
  { type: "color", key: "coreColor", label: "Hot core" },

  { type: "section", title: "Wisp shape" },
  {
    type: "slider",
    key: "dotRadius",
    label: "Dot radius",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    type: "slider",
    key: "dotSoft",
    label: "Dot soft",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    type: "slider",
    key: "coreAmp",
    label: "Core amp",
    min: 0,
    max: 3,
    step: 0.01,
  },
  {
    type: "slider",
    key: "bloomFalloff",
    label: "Bloom falloff",
    min: 0.5,
    max: 30,
    step: 0.1,
  },
  {
    type: "slider",
    key: "bloomAmp",
    label: "Bloom amp",
    min: 0,
    max: 2,
    step: 0.01,
  },
  {
    type: "slider",
    key: "overlapBloom",
    label: "Overlap bloom",
    min: 0,
    max: 1,
    step: 0.01,
  },

  { type: "section", title: "Camera" },
  {
    type: "slider",
    key: "cameraZ",
    label: "Distance (Z)",
    min: 0.5,
    max: 60,
    step: 0.5,
  },
  {
    type: "slider",
    key: "cameraY",
    label: "Height (Y)",
    min: -10,
    max: 20,
    step: 0.25,
  },
  {
    type: "slider",
    key: "cameraFov",
    label: "FOV",
    min: 20,
    max: 110,
    step: 1,
  },
]
