export type ConnectShaderConfig = {
  speed: number
  cylinderLength: number
  wavesX: number
  wavesY: number
  displacementHeight: number
  speedX: number
  speedY: number
  fillColor: string
  fillColor2: string
  fillGradScale: number
  fillAlpha: number
  fillLow: number
  fillHigh: number
  fillRadius: number
  lineColor: string
  lineCount: number
  lineWidth: number
  lineAlpha: number
  lineFadeLow: number
  lineFadeHigh: number
  hatchAngle: number
  hatchLift: number
  hatchSpacing: number
  hatchCell: number
  hatchFill: number
  dashMin: number
  dashMax: number
  hatchDensity: number
  densityFloor: number
  hatchDrift: number
  waveGate: number
  envCenter: number
  envSlope: number
  envWidth: number
  emitCount: number
  emitAmount: number
  emitSpeed: number
  emitDist: number
  emitFall: number
  emitSize: number
  emitStretch: number
  emitAlpha: number
  emitPaleColor: string
  emitSalmonColor: string
  emitOrangeColor: string
  emitAmberColor: string
  emitDeepColor: string
  paleColor: string
  salmonColor: string
  orangeColor: string
  amberColor: string
  deepColor: string
  cameraZ: number
  cameraY: number
  cameraFov: number
}

// @shader-config-start
export const CONNECT_SHADER_DEFAULTS = {
  speed: 1,
  cylinderLength: 100,
  wavesX: 3,
  wavesY: 3,
  displacementHeight: 3.4,
  speedX: 0.025,
  speedY: 0.13,
  fillColor: "#FF7A1F",
  fillColor2: "#FFAF36",
  fillGradScale: 1.6,
  fillAlpha: 0.9,
  fillLow: 0.38,
  fillHigh: 0.82,
  fillRadius: 1,
  lineColor: "#E8481C",
  lineCount: 180,
  lineWidth: 1,
  lineAlpha: 0.8,
  lineFadeLow: 0.35,
  lineFadeHigh: 0.72,
  hatchAngle: 90,
  hatchLift: 1.4,
  hatchSpacing: 0.22,
  hatchCell: 2.6,
  hatchFill: 0.8,
  dashMin: 0.15,
  dashMax: 0.95,
  hatchDensity: 2.1,
  densityFloor: 0.12,
  hatchDrift: 7,
  waveGate: 0.55,
  envCenter: 0.7,
  envSlope: 0.35,
  envWidth: 0.2,
  emitCount: 9000,
  emitAmount: 0.7,
  emitSpeed: 0.65,
  emitDist: 8,
  emitFall: 9,
  emitSize: 1.4,
  emitStretch: 6.5,
  emitAlpha: 0.95,
  emitPaleColor: "#FFE3D1",
  emitSalmonColor: "#FFB98C",
  emitOrangeColor: "#FF7A1F",
  emitAmberColor: "#FFA51F",
  emitDeepColor: "#E85D04",
  paleColor: "#FFE3D1",
  salmonColor: "#FFB98C",
  orangeColor: "#FF7A1F",
  amberColor: "#FFA51F",
  deepColor: "#E85D04",
  cameraZ: 18,
  cameraY: 4,
  cameraFov: 55,
} as const
// @shader-config-end
