import type { ShaderDevFieldDef } from "shader-panel"
import type { ConnectShaderConfig } from "./connect-shader-config"

export const CONNECT_SHADER_DEV_FIELDS: ShaderDevFieldDef<ConnectShaderConfig>[] =
  [
    { type: "section", title: "Global" },
    { type: "slider", key: "speed", label: "Speed", min: 0, max: 3, step: 0.05 },
    {
      type: "slider",
      key: "cylinderLength",
      label: "Cylinder length",
      min: 40,
      max: 260,
      step: 2,
    },
    { type: "section", title: "Wave" },
    {
      type: "slider",
      key: "wavesX",
      label: "Waves X",
      min: 0.2,
      max: 24,
      step: 0.1,
    },
    {
      type: "slider",
      key: "wavesY",
      label: "Waves Y",
      min: 0.2,
      max: 24,
      step: 0.1,
    },
    {
      type: "slider",
      key: "displacementHeight",
      label: "Displacement",
      min: 0,
      max: 24,
      step: 0.05,
    },
    {
      type: "slider",
      key: "speedX",
      label: "Drift X",
      min: 0,
      max: 0.6,
      step: 0.001,
    },
    {
      type: "slider",
      key: "speedY",
      label: "Drift Y",
      min: 0,
      max: 0.6,
      step: 0.001,
    },
    { type: "section", title: "Wave fill" },
    { type: "color", key: "fillColor", label: "Fill color A" },
    { type: "color", key: "fillColor2", label: "Fill color B" },
    {
      type: "slider",
      key: "fillGradScale",
      label: "Gradient scale",
      min: 0.2,
      max: 6,
      step: 0.05,
    },
    {
      type: "slider",
      key: "fillRadius",
      label: "Fill radius",
      min: 0,
      max: 2,
      step: 0.02,
    },
    {
      type: "slider",
      key: "fillAlpha",
      label: "Fill opacity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "fillLow",
      label: "Fill start",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "fillHigh",
      label: "Fill peak",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "section", title: "Stripe lines" },
    { type: "color", key: "lineColor", label: "Line color" },
    {
      type: "slider",
      key: "lineCount",
      label: "Line count",
      min: 20,
      max: 1500,
      step: 2,
    },
    {
      type: "slider",
      key: "lineWidth",
      label: "Width (px)",
      min: 0.4,
      max: 4,
      step: 0.05,
    },
    {
      type: "slider",
      key: "lineAlpha",
      label: "Opacity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "lineFadeLow",
      label: "Dissolve low",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "lineFadeHigh",
      label: "Dissolve high",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "section", title: "Hatch dashes" },
    {
      type: "slider",
      key: "hatchAngle",
      label: "Angle (deg)",
      min: 0,
      max: 180,
      step: 0.5,
    },
    {
      type: "slider",
      key: "hatchLift",
      label: "Float height",
      min: 0,
      max: 14,
      step: 0.05,
    },
    {
      type: "slider",
      key: "hatchSpacing",
      label: "Row spacing",
      min: 0.02,
      max: 0.8,
      step: 0.005,
    },
    {
      type: "slider",
      key: "hatchCell",
      label: "Cell length",
      min: 0.2,
      max: 12,
      step: 0.05,
    },
    {
      type: "slider",
      key: "hatchFill",
      label: "Thickness",
      min: 0.1,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "dashMin",
      label: "Dash min",
      min: 0.01,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "dashMax",
      label: "Dash max",
      min: 0.05,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "hatchDensity",
      label: "Density",
      min: 0,
      max: 8,
      step: 0.02,
    },
    {
      type: "slider",
      key: "densityFloor",
      label: "Density floor",
      min: 0,
      max: 1,
      step: 0.005,
    },
    {
      type: "slider",
      key: "hatchDrift",
      label: "Drift",
      min: 0,
      max: 40,
      step: 0.1,
    },
    {
      type: "slider",
      key: "waveGate",
      label: "Wave gating",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "section", title: "Hatch swath" },
    {
      type: "slider",
      key: "envCenter",
      label: "Swath center",
      min: 0,
      max: 1.2,
      step: 0.01,
    },
    {
      type: "slider",
      key: "envSlope",
      label: "Swath slope",
      min: -1,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "envWidth",
      label: "Swath width",
      min: 0.03,
      max: 0.6,
      step: 0.005,
    },
    { type: "section", title: "Particles" },
    {
      type: "slider",
      key: "emitCount",
      label: "Count",
      min: 500,
      max: 40000,
      step: 500,
    },
    {
      type: "slider",
      key: "emitAmount",
      label: "Amount",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "emitSpeed",
      label: "Launch rate",
      min: 0,
      max: 6,
      step: 0.01,
    },
    {
      type: "slider",
      key: "emitDist",
      label: "Fly distance",
      min: 0,
      max: 50,
      step: 0.1,
    },
    {
      type: "slider",
      key: "emitFall",
      label: "Fall w/ wave",
      min: 0,
      max: 80,
      step: 0.25,
    },
    {
      type: "slider",
      key: "emitSize",
      label: "Size (units)",
      min: 0.2,
      max: 16,
      step: 0.05,
    },
    {
      type: "slider",
      key: "emitStretch",
      label: "Stretch",
      min: 1,
      max: 20,
      step: 0.1,
    },
    {
      type: "slider",
      key: "emitAlpha",
      label: "Opacity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "color", key: "emitPaleColor", label: "Pale" },
    { type: "color", key: "emitSalmonColor", label: "Salmon" },
    { type: "color", key: "emitOrangeColor", label: "Orange" },
    { type: "color", key: "emitAmberColor", label: "Amber" },
    { type: "color", key: "emitDeepColor", label: "Deep" },
    { type: "section", title: "Hatch palette" },
    { type: "color", key: "paleColor", label: "Pale" },
    { type: "color", key: "salmonColor", label: "Salmon" },
    { type: "color", key: "orangeColor", label: "Orange" },
    { type: "color", key: "amberColor", label: "Amber" },
    { type: "color", key: "deepColor", label: "Deep" },
    { type: "section", title: "Camera" },
    {
      type: "slider",
      key: "cameraZ",
      label: "Distance (Z)",
      min: 0.5,
      max: 60,
      step: 0.5,
    },
    {
      type: "slider",
      key: "cameraY",
      label: "Height (Y)",
      min: -10,
      max: 20,
      step: 0.25,
    },
    {
      type: "slider",
      key: "cameraFov",
      label: "FOV",
      min: 20,
      max: 110,
      step: 1,
    },
  ]
