import type { ShaderDevFieldDef } from "shader-panel"
import type { ConnectShaderConfig } from "./connect-shader-config"

export const CONNECT_SHADER_DEV_FIELDS: ShaderDevFieldDef<ConnectShaderConfig>[] =
  [
    { type: "section", title: "Global" },
    { type: "slider", key: "speed", label: "Speed", min: 0, max: 3, step: 0.05 },
    { type: "section", title: "Shape" },
    {
      type: "select",
      key: "shapeType",
      label: "Shape type",
      layout: "stacked",
      options: [
        { value: "spiral", label: "Spiral cylinder" },
        { value: "plane", label: "Flat plane" },
        { value: "helix", label: "Helix" },
        { value: "ribbon", label: "Bent ribbon" },
        { value: "torus", label: "Torus" },
        { value: "mobius", label: "Möbius strip" },
        { value: "saddle", label: "Saddle" },
        { value: "waveSheet", label: "Wave sheet" },
        { value: "cone", label: "Cone spiral" },
        { value: "disc", label: "Disc" },
      ],
      description:
        "Base surface topology — wave, hatch, and emitter all follow this mesh.",
    },
    {
      type: "slider",
      key: "shapeWidth",
      label: "Surface width",
      min: 8,
      max: 48,
      step: 0.5,
      description: "Spiral, plane, ribbon, saddle, wave sheet.",
    },
    {
      type: "slider",
      key: "cylinderLength",
      label: "Surface length",
      min: 40,
      max: 260,
      step: 2,
      description: "Axial extent for sheet shapes; scales torus/möbius loop size.",
    },
    {
      type: "slider",
      key: "twistX",
      label: "Twist X",
      min: 0.05,
      max: 2.5,
      step: 0.01,
      description: "Spiral + cone — circumferential twist contribution.",
    },
    {
      type: "slider",
      key: "twistY",
      label: "Twist Y",
      min: 0.05,
      max: 2.5,
      step: 0.01,
      description: "Spiral + cone — axial twist rate.",
    },
    {
      type: "slider",
      key: "shapeRadius",
      label: "Radius",
      min: 3,
      max: 36,
      step: 0.25,
      description: "Helix, torus, möbius, disc.",
    },
    {
      type: "slider",
      key: "shapeConeRadiusStart",
      label: "Cone base radius",
      min: 0.5,
      max: 36,
      step: 0.25,
      description:
        "Cone spiral — radius at the bottom (wide end). Larger = wider base.",
    },
    {
      type: "slider",
      key: "shapeConeRadiusEnd",
      label: "Cone apex radius",
      min: 0,
      max: 36,
      step: 0.25,
      description:
        "Cone spiral — radius at the top (tip). Use 0–1 for a sharp point.",
    },
    {
      type: "slider",
      key: "shapeTube",
      label: "Tube radius",
      min: 0.5,
      max: 14,
      step: 0.1,
      description: "Torus cross-section thickness.",
    },
    {
      type: "slider",
      key: "shapeBend",
      label: "Bend amount",
      min: 0,
      max: 28,
      step: 0.25,
      description: "Ribbon sine sweep amplitude.",
    },
    {
      type: "slider",
      key: "shapePitch",
      label: "Helix pitch",
      min: 6,
      max: 90,
      step: 1,
      description: "Helix — Y distance per full rotation.",
    },
    {
      type: "slider",
      key: "shapeAmplitude",
      label: "Shape amplitude",
      min: 0,
      max: 24,
      step: 0.25,
      description: "Saddle depth, wave sheet hills, disc ripple.",
    },
    {
      type: "slider",
      key: "shapeTurns",
      label: "Turns / loops",
      min: 0.25,
      max: 5,
      step: 0.05,
      description: "Helix, ribbon, möbius, disc — wrap count.",
    },
    {
      type: "slider",
      key: "shapeWaveFreq",
      label: "Shape wave freq",
      min: 0.5,
      max: 8,
      step: 0.1,
      description: "Wave sheet + disc baked ripple frequency.",
    },
    { type: "section", title: "Wave" },
    {
      type: "slider",
      key: "wavesX",
      label: "Waves X",
      min: 0.2,
      max: 24,
      step: 0.1,
    },
    {
      type: "slider",
      key: "wavesY",
      label: "Waves Y",
      min: 0.2,
      max: 24,
      step: 0.1,
    },
    {
      type: "slider",
      key: "displacementHeight",
      label: "Displacement",
      min: 0,
      max: 24,
      step: 0.05,
    },
    {
      type: "slider",
      key: "speedX",
      label: "Drift X",
      min: 0,
      max: 0.6,
      step: 0.001,
    },
    {
      type: "slider",
      key: "speedY",
      label: "Drift Y",
      min: 0,
      max: 0.6,
      step: 0.001,
    },
    { type: "section", title: "Wave fill" },
    { type: "color", key: "fillColor", label: "Fill color A" },
    { type: "color", key: "fillColor2", label: "Fill color B" },
    {
      type: "slider",
      key: "fillGradScale",
      label: "Gradient scale",
      min: 0.2,
      max: 6,
      step: 0.05,
    },
    {
      type: "slider",
      key: "fillRadius",
      label: "Fill radius",
      min: 0,
      max: 2,
      step: 0.02,
    },
    {
      type: "slider",
      key: "fillAlpha",
      label: "Fill opacity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "fillLow",
      label: "Fill start",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "fillHigh",
      label: "Fill peak",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "section", title: "Stripe lines" },
    { type: "color", key: "lineColor", label: "Line color" },
    {
      type: "slider",
      key: "lineCount",
      label: "Line count",
      min: 20,
      max: 1500,
      step: 2,
    },
    {
      type: "slider",
      key: "lineWidth",
      label: "Width (px)",
      min: 0.4,
      max: 4,
      step: 0.05,
    },
    {
      type: "slider",
      key: "lineAlpha",
      label: "Opacity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "lineFadeLow",
      label: "Dissolve low",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "lineFadeHigh",
      label: "Dissolve high",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "section", title: "Hatch dashes" },
    {
      type: "slider",
      key: "hatchAngle",
      label: "Angle (deg)",
      min: 0,
      max: 180,
      step: 0.5,
    },
    {
      type: "slider",
      key: "hatchLift",
      label: "Float height",
      min: 0,
      max: 14,
      step: 0.05,
    },
    {
      type: "slider",
      key: "hatchSpacing",
      label: "Row spacing",
      min: 0.02,
      max: 0.8,
      step: 0.005,
    },
    {
      type: "slider",
      key: "hatchCell",
      label: "Cell length",
      min: 0.2,
      max: 12,
      step: 0.05,
    },
    {
      type: "slider",
      key: "hatchFill",
      label: "Thickness",
      min: 0.1,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "dashMin",
      label: "Dash min",
      min: 0.01,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "dashMax",
      label: "Dash max",
      min: 0.05,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "hatchDensity",
      label: "Density",
      min: 0,
      max: 8,
      step: 0.02,
    },
    {
      type: "slider",
      key: "densityFloor",
      label: "Density floor",
      min: 0,
      max: 1,
      step: 0.005,
    },
    {
      type: "slider",
      key: "hatchDrift",
      label: "Drift",
      min: 0,
      max: 40,
      step: 0.1,
    },
    {
      type: "slider",
      key: "waveGate",
      label: "Wave gating",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "section", title: "Hatch swath" },
    {
      type: "slider",
      key: "envCenter",
      label: "Swath center",
      min: 0,
      max: 1.2,
      step: 0.01,
    },
    {
      type: "slider",
      key: "envSlope",
      label: "Swath slope",
      min: -1,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "envWidth",
      label: "Swath width",
      min: 0.03,
      max: 0.6,
      step: 0.005,
    },
    { type: "section", title: "Particles" },
    {
      type: "slider",
      key: "emitCount",
      label: "Count",
      min: 500,
      max: 40000,
      step: 500,
    },
    {
      type: "slider",
      key: "emitAmount",
      label: "Amount",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "emitSpeed",
      label: "Launch rate",
      min: 0,
      max: 6,
      step: 0.01,
    },
    {
      type: "slider",
      key: "emitDist",
      label: "Fly distance",
      min: 0,
      max: 50,
      step: 0.1,
    },
    {
      type: "slider",
      key: "emitFall",
      label: "Fall w/ wave",
      min: 0,
      max: 80,
      step: 0.25,
    },
    {
      type: "slider",
      key: "emitSize",
      label: "Size (units)",
      min: 0.2,
      max: 16,
      step: 0.05,
    },
    {
      type: "slider",
      key: "emitStretch",
      label: "Stretch",
      min: 1,
      max: 20,
      step: 0.1,
    },
    {
      type: "slider",
      key: "emitAlpha",
      label: "Opacity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    { type: "color", key: "emitPaleColor", label: "Pale" },
    { type: "color", key: "emitSalmonColor", label: "Salmon" },
    { type: "color", key: "emitOrangeColor", label: "Orange" },
    { type: "color", key: "emitAmberColor", label: "Amber" },
    { type: "color", key: "emitDeepColor", label: "Deep" },
    { type: "section", title: "Hatch palette" },
    { type: "color", key: "paleColor", label: "Pale" },
    { type: "color", key: "salmonColor", label: "Salmon" },
    { type: "color", key: "orangeColor", label: "Orange" },
    { type: "color", key: "amberColor", label: "Amber" },
    { type: "color", key: "deepColor", label: "Deep" },
    { type: "section", title: "Render quality" },
    {
      type: "slider",
      key: "renderDpr",
      label: "Pixel ratio (DPR)",
      min: 0.5,
      max: 3,
      step: 0.05,
      description:
        "Canvas supersampling — higher = sharper lines/hatch, heavier GPU load.",
    },
    {
      type: "slider",
      key: "shapeMeshQuality",
      label: "Shape mesh density",
      min: 0.25,
      max: 3,
      step: 0.05,
      description:
        "Surface subdivisions — more points = smoother curves on all shapes.",
    },
    {
      type: "toggle",
      key: "renderAntialias",
      label: "MSAA antialias",
      description: "WebGL multisampling — toggling remounts the canvas.",
    },
    { type: "section", title: "Camera" },
    {
      type: "slider",
      key: "cameraZ",
      label: "Distance (Z)",
      min: 0.5,
      max: 60,
      step: 0.5,
    },
    {
      type: "slider",
      key: "cameraY",
      label: "Height (Y)",
      min: -10,
      max: 20,
      step: 0.25,
    },
    {
      type: "slider",
      key: "cameraFov",
      label: "FOV",
      min: 20,
      max: 110,
      step: 1,
    },
    { type: "section", title: "Post FX" },
    {
      type: "toggle",
      key: "postEnabled",
      label: "Enable post FX",
      description: "Single-pass blur, bokeh, grade — one extra fullscreen draw.",
    },
    {
      type: "select",
      key: "postPreset",
      label: "Preset",
      layout: "stacked",
      description:
        "Presets set a base look; sliders add on top (or multiply grade). Off/Custom = sliders only.",
      options: [
        { value: "off", label: "Off" },
        { value: "soft", label: "Soft glow" },
        { value: "cinematic", label: "Cinematic" },
        { value: "dreamy", label: "Dreamy haze" },
        { value: "punchy", label: "Punchy" },
        { value: "bloom", label: "Particle bloom" },
        { value: "retro", label: "Retro lens" },
        { value: "flare", label: "Lens flare" },
        { value: "custom", label: "Custom" },
      ],
    },
    {
      type: "slider",
      key: "postBlur",
      label: "Blur",
      min: 0,
      max: 1,
      step: 0.01,
      description: "Adds uniform blur on top of the preset.",
    },
    {
      type: "slider",
      key: "postBokeh",
      label: "Bokeh / bloom",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postBokehThreshold",
      label: "Bokeh threshold",
      min: 0.2,
      max: 0.95,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postChroma",
      label: "Chromatic aberration",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postVignette",
      label: "Vignette",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postGrain",
      label: "Film grain",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postExposure",
      label: "Exposure",
      min: 0.5,
      max: 2,
      step: 0.01,
      description: "Multiplies preset exposure when a preset is active.",
    },
    {
      type: "slider",
      key: "postContrast",
      label: "Contrast",
      min: 0.5,
      max: 1.8,
      step: 0.01,
      description: "Multiplies preset contrast when a preset is active.",
    },
    {
      type: "slider",
      key: "postSaturation",
      label: "Saturation",
      min: 0,
      max: 2,
      step: 0.01,
      description: "Multiplies preset saturation when a preset is active.",
    },
    {
      type: "slider",
      key: "postSharpness",
      label: "Sharpness",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postWarmth",
      label: "Warmth",
      min: -1,
      max: 1,
      step: 0.01,
      description: "Negative = cooler cast, positive = warmer.",
    },
    { type: "section", title: "Progressive blur" },
    {
      type: "slider",
      key: "postProgBlur",
      label: "Edge blur",
      min: 0,
      max: 1,
      step: 0.01,
      description: "Radial blur that ramps up toward the frame edges.",
    },
    {
      type: "slider",
      key: "postProgFocus",
      label: "Focus size",
      min: 0,
      max: 1,
      step: 0.01,
      description: "Sharp center region — higher keeps the middle clearer.",
    },
    { type: "section", title: "Lens flare" },
    {
      type: "slider",
      key: "postFlare",
      label: "Flare intensity",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postFlareSpread",
      label: "Ghost spread",
      min: 0,
      max: 1,
      step: 0.01,
      description: "Neutral at 0.5 when stacking on a preset.",
    },
    {
      type: "slider",
      key: "postFlareThreshold",
      label: "Flare threshold",
      min: 0.4,
      max: 0.98,
      step: 0.01,
      description: "Neutral at 0.72 when stacking on a preset.",
    },
    {
      type: "slider",
      key: "postFlareX",
      label: "Flare X",
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      type: "slider",
      key: "postFlareY",
      label: "Flare Y",
      min: 0,
      max: 1,
      step: 0.01,
    },
  ]
