import type { ShaderDevFieldDef } from "shader-panel"
import type { WaveShaderConfig } from "./wave-shader-config"

export const WAVE_SHADER_DEV_FIELDS: ShaderDevFieldDef<WaveShaderConfig>[] = [
  { type: "section", title: "Waves" },
  {
    type: "slider",
    key: "wavesX",
    label: "Waves X",
    min: 0.2,
    max: 10,
    step: 0.1,
  },
  {
    type: "slider",
    key: "wavesY",
    label: "Waves Y",
    min: 0.2,
    max: 10,
    step: 0.1,
  },
  {
    type: "slider",
    key: "displacementHeight",
    label: "Displacement",
    min: 0,
    max: 8,
    step: 0.05,
  },
  { type: "section", title: "Drift speed" },
  {
    type: "slider",
    key: "speedX",
    label: "Speed X",
    min: 0,
    max: 0.2,
    step: 0.001,
  },
  {
    type: "slider",
    key: "speedY",
    label: "Speed Y",
    min: 0,
    max: 0.2,
    step: 0.001,
  },
  { type: "section", title: "Colors" },
  { type: "color", key: "primaryColor", label: "Primary" },
  { type: "color", key: "valleyColor", label: "Valley" },
  { type: "color", key: "peakColor", label: "Peak" },
  { type: "section", title: "Visibility band" },
  {
    type: "slider",
    key: "visibleBand",
    label: "Band cutoff",
    min: 0,
    max: 2,
    step: 0.01,
  },
  {
    type: "slider",
    key: "visibleFade",
    label: "Band fade",
    min: 0,
    max: 1,
    step: 0.01,
  },
  { type: "section", title: "Camera" },
  {
    type: "slider",
    key: "cameraZ",
    label: "Distance (Z)",
    min: 0.5,
    max: 60,
    step: 0.5,
  },
  {
    type: "slider",
    key: "cameraY",
    label: "Height (Y)",
    min: -10,
    max: 20,
    step: 0.25,
  },
  {
    type: "slider",
    key: "cameraFov",
    label: "FOV",
    min: 20,
    max: 110,
    step: 1,
  },
]
